//! Integration tests for `ExtensionRuntime::invoke_composer_*` methods.
//!
//! Uses a minimal hand-crafted WAT component that exports
//! `greentic:dw-composer/composer@0.1.0` with stub implementations,
//! mirroring the fixture pattern used in `runtime_load.rs` and
//! `roles_smoke.rs` — sign a describe.json, register the extension, invoke
//! the method under test.
//!
//! The WAT was derived via `wasm-tools component embed` +
//! `wasm-tools component new` against the canonical WIT in
//! `wit/extension-dw-composer.wit`. The stub implementations return static
//! in-memory JSON blobs, which is enough to prove the wasmtime dispatch path.

#[path = "support/mod.rs"]
mod support;

use std::path::PathBuf;

use greentic_ext_runtime::{DiscoveryPaths, ExtensionRuntime, RuntimeConfig, RuntimeError};
use greentic_extension_sdk_contract::ExtensionKind;

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

/// Build the WAT bytes for a minimal composer component.
///
/// The component exports `greentic:dw-composer/composer@0.1.0` with stub
/// implementations that return static JSON blobs:
///   - `metadata` -> `{"id":"test","name":"Test Composer"}`
///   - `compose`  -> `Ok("{\"id\":\"test\",\"name\":\"Test Composer\"}")`
///   - `validate` -> `"[]"`
///   - `templates` -> `"[]"`
///
/// The WAT encodes the full Component Model canonical ABI (canon lift,
/// post-return, realloc) so wasmtime can instantiate and call it without
/// additional adapter layers.
fn build_composer_wasm() -> Vec<u8> {
    // The WAT below was generated by running:
    //   wasm-tools component embed <wit-dir> composer_core.wat -o embedded.wasm
    //   wasm-tools component new embedded.wasm -o component.wasm
    //   wasm-tools print component.wasm
    // The core module uses static data segments, so no heap allocation is needed.
    let wat = r#"
(component
  (core module $main
    (type (;0;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;1;) (func (result i32)))
    (type (;2;) (func (param i32)))
    (type (;3;) (func (param i32 i32) (result i32)))
    (memory (;0;) 1)
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 0))
    (export "greentic:dw-composer/composer@0.1.0#metadata" (func 1))
    (export "cabi_post_greentic:dw-composer/composer@0.1.0#metadata" (func 2))
    (export "greentic:dw-composer/composer@0.1.0#templates" (func 3))
    (export "cabi_post_greentic:dw-composer/composer@0.1.0#templates" (func 4))
    (export "greentic:dw-composer/composer@0.1.0#compose" (func 5))
    (export "cabi_post_greentic:dw-composer/composer@0.1.0#compose" (func 6))
    (export "greentic:dw-composer/composer@0.1.0#validate" (func 7))
    (export "cabi_post_greentic:dw-composer/composer@0.1.0#validate" (func 8))
    (func (;0;) (type 0) (param i32 i32 i32 i32) (result i32)
      local.get 3
    )
    (func (;1;) (type 1) (result i32)
      i32.const 512
    )
    (func (;2;) (type 2) (param i32))
    (func (;3;) (type 1) (result i32)
      i32.const 528
    )
    (func (;4;) (type 2) (param i32))
    (func (;5;) (type 3) (param i32 i32) (result i32)
      i32.const 544
    )
    (func (;6;) (type 2) (param i32))
    (func (;7;) (type 3) (param i32 i32) (result i32)
      i32.const 528
    )
    (func (;8;) (type 2) (param i32))
    ;; metadata JSON at 0 (36 bytes), "[]" at 36 (2 bytes)
    (data (;0;) (i32.const 0) "{\"id\":\"test\",\"name\":\"Test Composer\"}")
    (data (;1;) (i32.const 36) "[]")
    ;; Result tuple for metadata at 512: (ptr=0, len=36) — 0x24 = 36
    (data (;2;) (i32.const 512) "\00\00\00\00\24\00\00\00")
    ;; Result tuple for templates at 528: (ptr=36, len=2) — 0x24 = 36
    (data (;3;) (i32.const 528) "\24\00\00\00\02\00\00\00")
    ;; result<string, string> for compose at 544: (disc=0=ok, ptr=0, len=36)
    (data (;4;) (i32.const 544) "\00\00\00\00\00\00\00\00\24\00\00\00")
  )
  (core instance $main (instantiate $main))
  (alias core export $main "memory" (core memory $memory))
  (type (;0;) (func (result string)))
  (alias core export $main "greentic:dw-composer/composer@0.1.0#metadata" (core func $fn_metadata))
  (alias core export $main "cabi_realloc" (core func $cabi_realloc))
  (alias core export $main "cabi_post_greentic:dw-composer/composer@0.1.0#metadata" (core func $post_metadata))
  (func $metadata (type 0) (canon lift (core func $fn_metadata) (memory $memory) string-encoding=utf8 (post-return $post_metadata)))
  (type (;1;) (result string (error string)))
  (type (;2;) (func (param "intent-json" string) (result 1)))
  (alias core export $main "greentic:dw-composer/composer@0.1.0#compose" (core func $fn_compose))
  (alias core export $main "cabi_post_greentic:dw-composer/composer@0.1.0#compose" (core func $post_compose))
  (func $compose (type 2) (canon lift (core func $fn_compose) (memory $memory) (realloc $cabi_realloc) string-encoding=utf8 (post-return $post_compose)))
  (type (;3;) (func (param "manifest-json" string) (result string)))
  (alias core export $main "greentic:dw-composer/composer@0.1.0#validate" (core func $fn_validate))
  (alias core export $main "cabi_post_greentic:dw-composer/composer@0.1.0#validate" (core func $post_validate))
  (func $validate (type 3) (canon lift (core func $fn_validate) (memory $memory) (realloc $cabi_realloc) string-encoding=utf8 (post-return $post_validate)))
  (type (;4;) (func (result string)))
  (alias core export $main "greentic:dw-composer/composer@0.1.0#templates" (core func $fn_templates))
  (alias core export $main "cabi_post_greentic:dw-composer/composer@0.1.0#templates" (core func $post_templates))
  (func $templates (type 4) (canon lift (core func $fn_templates) (memory $memory) string-encoding=utf8 (post-return $post_templates)))
  (component $shim
    (type (;0;) (func (result string)))
    (import "import-func-metadata" (func (;0;) (type 0)))
    (type (;1;) (result string (error string)))
    (type (;2;) (func (param "intent-json" string) (result 1)))
    (import "import-func-compose" (func (;1;) (type 2)))
    (type (;3;) (func (param "manifest-json" string) (result string)))
    (import "import-func-validate" (func (;2;) (type 3)))
    (import "import-func-templates" (func (;3;) (type 0)))
    (export "metadata" (func 0))
    (export "compose" (func 1))
    (export "validate" (func 2))
    (export "templates" (func 3))
  )
  (instance $shim_inst (instantiate $shim
      (with "import-func-metadata" (func $metadata))
      (with "import-func-compose" (func $compose))
      (with "import-func-validate" (func $validate))
      (with "import-func-templates" (func $templates))
    )
  )
  (export "greentic:dw-composer/composer@0.1.0" (instance $shim_inst))
)
"#;
    wat::parse_str(wat).expect("composer fixture WAT must compile")
}

/// Build a signed fixture with the composer component WASM.
///
/// Uses `ExtensionKind::Design` because the SDK contract does not yet have a
/// `DwComposer` variant; the kind only affects the discovery directory layout,
/// not the WIT interface lookup performed by the runtime.
fn build_signed_composer_fixture(
    ext_id: &str,
    version: &str,
) -> (
    greentic_extension_sdk_testing::ExtensionFixture,
    ed25519_dalek::SigningKey,
) {
    use ed25519_dalek::SigningKey;
    use rand::rngs::OsRng;

    let wasm_bytes = build_composer_wasm();
    let fixture = greentic_extension_sdk_testing::ExtensionFixtureBuilder::new(
        ExtensionKind::Design,
        ext_id,
        version,
    )
    .offer("greentic:test/composer-ping", "1.0.0")
    .with_wasm(wasm_bytes)
    .build()
    .expect("fixture build");

    let describe_path = fixture.root().join("describe.json");
    let raw = std::fs::read_to_string(&describe_path).unwrap();
    let mut describe: greentic_extension_sdk_contract::DescribeJson =
        serde_json::from_str(&raw).unwrap();
    support::populate_gtpack_for_local_load(&mut describe);
    let sk = SigningKey::generate(&mut OsRng);
    support::finalize_signed_with_manifest(fixture.root(), &mut describe, &sk);

    (fixture, sk)
}

// ---------------------------------------------------------------------------
// Tests: error cases (no extension loaded)
// ---------------------------------------------------------------------------

#[test]
fn invoke_composer_metadata_returns_not_found_when_no_extension_loaded() {
    let dir = tempfile::tempdir().expect("tempdir");
    let config = RuntimeConfig::from_paths(DiscoveryPaths::new(dir.path().to_path_buf()));
    let runtime = ExtensionRuntime::new(config).expect("new runtime");

    let error = runtime
        .invoke_composer_metadata("greentic.dw.composer.banking-id-1.3.0-research")
        .unwrap_err();

    assert!(
        matches!(error, RuntimeError::NotFound(_)),
        "expected NotFound, got {error:?}"
    );
}

#[test]
fn invoke_composer_compose_returns_not_found_when_no_extension_loaded() {
    let dir = tempfile::tempdir().expect("tempdir");
    let config = RuntimeConfig::from_paths(DiscoveryPaths::new(dir.path().to_path_buf()));
    let runtime = ExtensionRuntime::new(config).expect("new runtime");

    let error = runtime
        .invoke_composer_compose("does.not.exist", r#"{"intent":"open-account"}"#)
        .unwrap_err();

    assert!(
        matches!(error, RuntimeError::NotFound(_)),
        "expected NotFound, got {error:?}"
    );
}

// ---------------------------------------------------------------------------
// Tests: happy path with the stub composer fixture
// ---------------------------------------------------------------------------

#[test]
fn invoke_composer_metadata_returns_descriptor_json() {
    let (fixture, _sk) = build_signed_composer_fixture("greentic.dw.composer.test", "0.1.0");

    // Trust root must be a temp dir: the default is the developer's real
    // ~/.greentic, and the fixture is signed with a fresh key per call.
    let trust = tempfile::TempDir::new().expect("temp trust root");
    let config = RuntimeConfig::from_paths(DiscoveryPaths::new(PathBuf::from("/dev/null")))
        .with_trust_root(trust.path().to_path_buf());
    let mut runtime = ExtensionRuntime::new(config).expect("new runtime");
    runtime
        .register_loaded_from_dir(fixture.root())
        .expect("register composer extension");

    let metadata_json = runtime
        .invoke_composer_metadata("greentic.dw.composer.test")
        .expect("invoke_composer_metadata should succeed");

    // The stub returns {"id":"test","name":"Test Composer"}.
    let parsed: serde_json::Value =
        serde_json::from_str(&metadata_json).expect("metadata should be valid JSON");
    assert_eq!(parsed["id"], "test", "expected id='test', got: {parsed:#}");
    assert_eq!(
        parsed["name"], "Test Composer",
        "expected name='Test Composer', got: {parsed:#}"
    );
}

#[test]
fn invoke_composer_compose_returns_ok_manifest_json() {
    let (fixture, _sk) =
        build_signed_composer_fixture("greentic.dw.composer.compose-test", "0.1.0");

    // Trust root must be a temp dir: the default is the developer's real
    // ~/.greentic, and the fixture is signed with a fresh key per call.
    let trust = tempfile::TempDir::new().expect("temp trust root");
    let config = RuntimeConfig::from_paths(DiscoveryPaths::new(PathBuf::from("/dev/null")))
        .with_trust_root(trust.path().to_path_buf());
    let mut runtime = ExtensionRuntime::new(config).expect("new runtime");
    runtime
        .register_loaded_from_dir(fixture.root())
        .expect("register composer extension");

    let result = runtime
        .invoke_composer_compose(
            "greentic.dw.composer.compose-test",
            r#"{"intent":"open-savings-account","currency":"EUR"}"#,
        )
        .expect("invoke_composer_compose host call should succeed");

    // The stub always returns Ok(metadata_json).
    let manifest_json = result.expect("stub compose should return Ok");
    assert!(
        !manifest_json.is_empty(),
        "returned manifest JSON should not be empty"
    );
    // Verify it's parseable JSON.
    serde_json::from_str::<serde_json::Value>(&manifest_json)
        .expect("compose Ok value should be valid JSON");
}
